name: Integration tests

on: 
  push:
  schedule:
    - cron:  '0 5 * * *'

jobs:
  tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
      - name: Install dependencies
        run: |
          pip install -U pip
          pip install -e .
          pip install -r requirements.dev.txt
      - name: Lint with flake8
        run: |
          flake8 tests src
      - name: Run static typing check
        run: |
          mypy src/potafloes
      - name: Run tests
        run: |
          pytest
